### ISSUE TITLE
Failure to correctly detect RHEL 8 on some systems.

### ISSUE THREAD

**Issue by edwbuck** [MapRPS/cluster-validation#1]
**Describe the bug**
On RHEL 8.6 and RHEL 8.8 systems, the Distro checks in the pre-install/cluster-audit.sh script fails to detect the distro as a supported RHEL 8 distro.

**To Reproduce**
1. run cluster-audit.sh.
2. Notice that it exits saying it is not a supported distro.

**Expected behavior**
cluster-audit.sh should detect that the RHEL 8.6 and RHEL 8.8 distros are supported, and indicate that they are supported as RHEL 8 distros.

**Desktop (please complete the following information):**
 - m2-pf-vm75

**Comment by sj6** [comment]
Hello

Just tested it out and it works now flawlessly.

OS: Red Hat 8.8
Kernel: 4.18.0-477.27.1.el8_8.x86_64

Thanks a lot @edwbuck 

Regards,
Sayan
